server:
  port: 8086
 
oauth:
  server:
    authorize-url: https://localhost/oauth/authorize/
    token-url: https://localhost/oauth/token
    #jwk-url: https://localhost/oauth/jwk
    expected-signature-algorithm: NONE   # EC256 or RS256 or NONE
    
  trusted-client:
    key: dVs2IYWeRSioKOsfP5Gv8A
    secret: 0-dtHdO_SMODM_x8uoOKrQ
    #scope: view-records-all
    redirect-uri: http://localhost:8086/api/oauth/redirect

  public-client:
    key: DmDnVNSfQEuQXA6v1s2HhA
    #scope: change-address view-grades
    redirect-uri: http://localhost:8086/api/oauth/redirect
    
