server:
  port: 8086
 
oauth:
  server:
    authorize-url: https://localhost:8443/oauth/authorize
    tenant-id: VSGpKYfVRGaSG0np31jxHg
    organization-id: cWvbPa9VTpGXqDk_bZy0ew
    token-url: https://localhost:8443/oauth/tenants/tenantId/organizations/organizationId/token
    jwk-url: https://localhost:8443/oauth/tenants/tenantId/organizations/organizationId/jwk
    
  client:
    key: XPOnkRPuRFSFx65hnUmuCw
    secret: rpDuoW-mTYCcnmZecFdaFw
    scope: email:read userinfo:read
    redirect-uri: http://localhost:8086/api/authcode
    
