server:
  port: 8086
 
oauth:
  server:
    authorize-url: https://localhost:8443/oauth/authorize/
    tenant-id: YYkqP3t2SgKqXdT-AQYNmQ
    organization-id: I_f1omAGRai0ST4DKPxVEA
    token-url: https://localhost:8443/oauth/tenantId/organizationId/token/
    jwk-url: https://localhost:8443/oauth/tenantId/organizationId/jwk
    expected-signature-algorithm: RS256   # EC256 or RS256
    
  trusted-client:
    key: dVs2IYWeRSioKOsfP5Gv8A
    secret: 0-dtHdO_SMODM_x8uoOKrQ
    #scope: view-records-all
    redirect-uri: http://localhost:8086/api/oauth/redirect

  public-client:
    key: DmDnVNSfQEuQXA6v1s2HhA
    #scope: change-address view-grades
    redirect-uri: http://localhost:8086/api/oauth/redirect
    
